### PR TITLE
Allow function in redirectTo in callback handler

### PR DESCRIPTION
**Pull request by steelbrain**
Right now the API accepts a string `redirectTo` in callback. This doesn't work when you want to do conditional callbacks. Current workaround is to add another "hop" url in the mix. That hop url houses the logic for where to send the user based on their session data. Think homepage vs onboarding.

With this PR change applied, we can remove that extra redirect hop and make the redirection decision in the callback API request.

### CODE REVIEW

**Comment by adamjmcgrath** [comment]
Hi @steelbrain - thanks for your contribution

I'd be happy to accept this if you raised it against the `beta` branch (note the callback option is called `returnTo` in the beta)

**Comment by adamjmcgrath** [comment]
fixes: #139

**Comment by steelbrain** [comment]
I checked out the new beta, this PR is no longer necessary.

image

We can modify the `openIdState` variable from `afterCallback`

**Comment by adamjmcgrath** [comment]
Ah - good catch! thanks @steelbrain

**Pull request closed without merging**
