### PR TITLE
allow the logout returnTo URL to be configurable at request-time

### LINKED ISSUE #117: Unable to redirect to a dynamic URL on logout
The ?redirectTo query param from v0.13.0 does not work for logouts. Also I see that handleLogout() doesn't accept any options making it impossible to redirect the user to a dynamic URL on log-out. This is necessary when redirecting the user back to a locale-specific URL.

### PR DESCRIPTION
**Pull request by lone-cloud**
Fixed #117 

### Checklist

- [✓] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [✓] All active GitHub checks for tests, formatting, and security are passing
- [✓] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by mayatools** [comment]
+1 to having this PR merged

**Comment by lone-cloud** [comment]
@sandrinodimattia what will it take :)

**Comment by mayatools** [comment]
<bump>

Any chance of this getting merged?

**Comment by mayatools** [comment]
<bump> :) Thx!

**Comment by sandrinodimattia** [comment]
Thanks for the PR 👍  Released under [v0.14](https://github.com/auth0/nextjs-auth0/releases/tag/v0.14.0)

**Comment by mayatools** [comment]
YAY...thank you!!

**Pull request merged**
