### PR TITLE
fix: load from `process.env.VERCEL_URL` if `AUTH0_BASE_URL` not set

### LINKED ISSUE #383: Need new guidance for VERCEL_URL and AUTH0_BASE_URL
The guidance in https://github.com/auth0/nextjs-auth0/blob/main/examples/README.md#environment-variables-1 needs to change.

We can no longer assign `VERCEL_URL` to `AUTH0_BASE_URL` using "Reference to System Environment Variable" in the Vercel dashboard.

> We previously introduced the Provided by System option as some frameworks need to map system variables like VERCEL_URL to framework prefixed variables like NEXT_PUBLIC_VERCEL_URL. You no longer need to configure this mapping because the prefixed variables are added automatically based on your Framework Preset.

Source: https://vercel.com/changelog/environments-variables-per-git-branch

We will need to suggest a way that developers can assign `VERCEL_URL` to `AUTH0_BASE_URL` when the application is running (note: we don't need `AUTH0_BASE_URL` at build time)

### PR DESCRIPTION
**Pull request by ctjlewis**
Potentially fixes #383.

### Description
See https://github.com/auth0/nextjs-auth0/issues/383#issuecomment-1026071966.

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `main`

### CODE REVIEW

**Comment by adamjmcgrath** [comment]
Hi @ctjlewis - thanks for raising this

We don't want to bake Vercel environment variables into the SDK if we can avoid it, so I'm going to close this.

Have a look at the instructions [here](https://github.com/auth0/nextjs-auth0/tree/main/examples#assigning-the-auth0_base_url) for assigning the `AUTH0_BASE_URL` when using Vercel and feel free to raise an issue if you find one.

**Comment by ctjlewis** [comment]
@adamjmcgrath I would really recommend reopening and merging this PR. Whatever logic behind not doing this automatically despite the library being designed for deployment to Vercel, it's not worth it. I have to look this PR up every time I add the library to a new file because it's the only way to keep the base URL consistent across real deploys.

**Comment by ctjlewis** [comment]
You know, it's still impossible to deploy a working dev environment to production without being incredibly crafty and realizing you have to manually shim the AUTH0_BASE_URL to match VERCEL_URL at runtime.

This is objectively suboptimal software design. Just terrible work.

**Comment by ctjlewis** [comment]
@adamjmcgrath I think about this every time I need to hack this together manually in a new project because it will otherwise not recognize the correct base URL at a deploy URL, which is obviously necessary for any site using this to run.

**Comment by adamjmcgrath** [comment]
Hi @ctjlewis - thanks for your feedback, and apologies we didn't accept your PR

Our instructions for assigning the `AUTH0_BASE_URL` for preview deployments on Vercel are here https://github.com/auth0/nextjs-auth0/tree/main/examples#assigning-the-auth0_base_url, this includes info for people that want to use the Automatic Deployment URL or Automatic Branch URL.

We also have instructions for handling production deployments in Vercel here https://github.com/auth0/nextjs-auth0/tree/main/examples#production-deployments-or-other-environments-with-fixed-urls - where we recommend using the Vercel dashboard

If you think these instructions are incorrect, feel free to raise an issue with steps to reproduce and we'd be happy to investigate it for you.

**Comment by tisonkun** [comment]
I try place `AUTH0_BASE_URL=${VERCEL_URL}` in `.env.production` under the root path but it doesn't work.

**Comment by ctjlewis** [comment]
> It doesn't work for me either. It seems that the preview deployment doesn't read `.env.production` for some reason. I'm using prebuilt projects with GitHub actions which I then deploy to Vercel.

Yeah, this team refuses to listen to me regarding the pattern. It should just read from VERCEL_URL automatically.

**For now, you must go into Project Settings > Environment Variables, and override `AUTH0_BASE_URL` for Production to your Production Domain URL.**  For instance, if my preview `site-abc.vercel.app` is deployed to `site.com` in production, you must go to Environment Variables and override `AUTH0_BASE_URL="site.com"`.

**Comment by tlazarov-whiskypartners** [comment]
@ctjlewis But how do you make it work for preview deployments? Here's my current GitHub actions workflow setup:
```
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: AUTH0_BASE_URL="http://0.0.0.0:3000" vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"
```

I'm setting `AUTH0_BASE_URL="http://0.0.0.0:3000"` to an temporary value during the build step, so that Auth0 doesn't complain about the `baseURL` missing, but then I can't use the preview URL for re-setting it after the deployment, because I only have access to the preview URL after it's been deployed.

**Comment by thexpand** [comment]
@ctjlewis But how do you make it work for preview deployments? Here's my current GitHub actions workflow setup:
```
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: AUTH0_BASE_URL="http://0.0.0.0:3000" vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"
```

I'm setting `AUTH0_BASE_URL="http://0.0.0.0:3000"` to a temporary value during the build step, so that Auth0 doesn't complain about the `baseURL` missing, but then I can't use the preview URL for re-setting it after the deployment, because I only have access to the preview URL after it's been deployed.

**Comment by ctjlewis** [comment]
@thexpand If I needed preview URLs to work I used to use this shim:

```
process.env.AUTH0_BASE_URL = process.env.AUTH0_BASE_URL || process.env.NEXT_PUBLIC_DOMAIN || process.env.VERCEL_URL;
```

But it's not convenient. The library generally poorly supports this despite being designed specifically for deploying on this exact architecture.

**Comment by thexpand** [comment]
Hmm, actually I got it working with a `.env` file instead of a `.env.production` one. This is the content of my `.env` (commited into VCS):
```
AUTH0_BASE_URL=$VERCEL_URL
```

And then the steps for my GitHub action for preview deployments are configured like this:
```
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: AUTH0_BASE_URL="http://0.0.0.0:3000" vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: echo "PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"
```

**Pull request closed without merging**
