### PR TITLE
feat: support customized shouldBypassReq logics

### PR DESCRIPTION
**Pull request by tisonkun**
### 📋 Changes

Support intercept hardcode bypass logic in `withMiddlewareAuthRequired`.

### 📎 References

#977

### 🎯 Testing

New tests in `tests/helpers/with-middleware-auth-required.test.ts`

Open for review.

### CODE REVIEW

**Comment by tisonkun** [comment]
@adamjmcgrath now I have one more reason to add this hook:

I'd like to bypass `img/favicon.ico`. With this patch it's more simple to [Match paths based on conditional statements](https://vercel.com/docs/concepts/functions/edge-middleware#match-paths-based-on-conditional-statements), instead of a complex regex like `/((?!img/favicon.ico).*)`.

**Comment by adamjmcgrath** [comment]
Hi @tisonkun - thanks for raising this

I still don't see this as a valid use case and it should be fairly trivial to add your own middleware with this behaviour using `getSession` (see https://github.com/auth0/nextjs-auth0#edge-for-middleware-and-the-edge-runtime)

But I'll continue to assess this based on other use cases that may come to light

**Comment by tisonkun** [comment]
@adamjmcgrath No. Before calling `getSession`, the middleware logic returned:

```js
const ignorePaths = [login, callback, unauthorized, '/_next', '/favicon.ico'];
      if (ignorePaths.some((p) => pathname.startsWith(p))) {
        return; // <-- NOTICE THIS LINE
```

So my own middleware hook has no change to be called.

**Comment by tisonkun** [comment]
To be clear, the control flow gets returned at L61:

https://github.com/auth0/nextjs-auth0/blob/5c15a1e17dc0f56bdcdc832c69a7b85aa260a73b/src/helpers/with-middleware-auth-required.ts#L60-L62

... while customized middleware gets called at L76:

https://github.com/auth0/nextjs-auth0/blob/f8d2dac8ad74030fb46d9b863b0324f418bacffa/src/helpers/with-middleware-auth-required.ts#L76

**Comment by adamjmcgrath** [comment]
@tisonkun - you don't need to use `withMiddlewareAuthRequired` to use `getSession`

```js
import { getSession } from '@auth0/nextjs-auth0/edge';
import { NextResponse } from 'next/server';

export default async function middleware(req) {
  // Ignore the paths you want
  const res = NextResponse.next();
  const user = await getSession(req, res);
  if (!user) {
    // redirect to login/401
  } else {
    return res;
  }
}

```

**Comment by tisonkun** [comment]
@adamjmcgrath Aha. That's it.

Previously, I try to copy the middleware logics from `withMiddlewareAuthRequiredFactory` and find some methods are not exported. But maybe I don't need them at all.

BTW, here is the remaining part I don't understand and wonder whether I should keep it when customized:

```ts
      if (res) {
        const headers = new Headers(res.headers);
        const cookies = headers.get('set-cookie')?.split(', ') || [];
        const authCookies = authRes.headers.get('set-cookie')?.split(', ') || [];
        if (cookies.length || authCookies.length) {
          headers.set('set-cookie', [...authCookies, ...cookies].join(', '));
        }
        return NextResponse.next({ ...res, status: res.status, headers });
      } else {
        return authRes;
      }
```

**Comment by tisonkun** [comment]
Finally I write something like:

```ts
export default async function middleware(req: NextRequest) {
    const {pathname, origin} = req.nextUrl

    const ignorePaths = ['/api/auth/login', '/api/auth/callback', '/api/auth/401', '/img/favicon.ico']
    if (ignorePaths.some((p) => pathname.startsWith(p))) return

    const res = NextResponse.next()
    const session = await getSession(req, res)

    if (!session?.user) {
        const unauthorized = NextResponse.rewrite(new URL('/api/auth/401', origin), {status: 401})
        const encodedReturnTo = encodeURIComponent(req.nextUrl.toString())
        const login = NextResponse.redirect(new URL(`/api/auth/login?returnTo=${encodedReturnTo}`, origin))
        return pathname.startsWith('/api') ? unauthorized : login
    }

    const user = session.user
    if (isWhitelistUser(user)) {
        if (path.extname(pathname)) return res
        if (pathname.startsWith('/api')) return res

        // WHAT: specially handle / or /docs case.
        //
        // WHY: Next.js will intercept these urls and result in a 404 page.
        // We should append an index.html segment to succeed in the first Docusaurus pages loading.
        // Then the Docusaurus SPA will take over the control flow.
        return NextResponse.redirect(new URL(path.resolve(pathname, 'index.html'), origin))
    }

    if (pathname.startsWith('/api/auth/logout')) return res

    const forbidden = new URL(`/api/auth/403?user=${encodeURIComponent(JSON.stringify(user))}`, origin)
    return NextResponse.rewrite(forbidden)
}
```

**Comment by adamjmcgrath** [comment]
> BTW, here is the remaining part I don't understand and wonder whether I should keep it when customized:

This ensures that any updates to the session during the lifecycle of the middleware are saved back in the cookie, if you're not updating the session (and don't mind that the cookie expires isn't updated to bump the [rolling session](https://auth0.github.io/nextjs-auth0/interfaces/config.sessionconfig.html#rolling)) you don't need it

**Pull request closed without merging**
